language: groovy

env:
    - TEST_SUITE=main_pg
    - TEST_SUITE=load_dump_load_pg
    - TEST_SUITE=R
    - TEST_SUITE=configuration_syntax
    - TEST_SUITE=main_oracle

addons:
    postgresql: "9.4"

before_install:
    - git clone --depth 1 git://github.com/thehyve/transmart-travis.git ~/ts-travis
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 3375DA21
    - echo deb http://apt.thehyve.net/internal/ trusty main | sudo tee /etc/apt/sources.list.d/hyve_internal.list
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E5267A6C
    - echo deb http://ppa.launchpad.net/ondrej/php5/ubuntu precise main  | sudo tee /etc/apt/sources.list.d/ondrej_php5.list
    - sudo apt-get update
    - sudo apt-get install -y tk-dev # while colorspace 1.2-6 is not out

install:
    - sudo apt-get install -qq php5-cli php5-json subversion
    - make -C env groovy
    - make -C env ../vars
    - sed -i 's@PGSQL_BIN=.*@PGSQL_BIN="sudo -E -u postgres /usr/lib/postgresql/9.4/bin/"@' vars

before_script:
    - ulimit -u 4096
    - export PATH=./env:$PATH
    - echo $(groovy --version)

script: ./travis-test $TEST_SUITE
